### ISSUE TITLE
PDF report diagram is split

### ISSUE THREAD

**Issue by kparris007** [OWASP/threat-dragon-core#26]
The threat model PDF report generated by the tool is splitting the diagram across pages. For example, when a 1-page diagram occurs half-way down a page. To overcome this issue, the user could insert a page-break just before the diagram or manually ensure the diagram does not occur over a page break.

**Comment by jgadsden** [comment]
Hello @kparris007 - this is a very good point, and it would be good to correct this. If you have a code patch for this that would be great

**Comment by jgadsden** [comment]
Hello @kparris007 - the pull request #30 corrects this. Thanks again for raising this
