### ISSUE TITLE
Editing/Removing a threat does not change the status of the diagram to dirty

### ISSUE THREAD

**Issue by andk123** [OWASP/threat-dragon-core#49]
**Describe the bug**
If you remove or edit a threat, it does not change the status of the diagram to dirty. Hence you do not receive an "unsaved changes" notification before exiting the edit page for the diagram.

**To Reproduce**
1. Go to Manage threats on the edit diagram page
2. Click on an existing threat.
3. Modify the existing threat and save
4. Close diagram without saving.
5. No notification
---alternatively from 2.
3b. Delete an existing threat (from a list of more than 1 threats)
4b. Close diagram without saving
5b. No notification

**Expected behavior**
There should be an "unsaved changes" notification before exiting the edit page.

**Screenshots**

**Environment:**
 - Platform: Desktop
 - OS: Windows

**Comment by andk123** [comment]
One solution to fix this issue required only changing one character in .\src\diagrams\elementpropdirectives.js on line 69:
`save: '&'`
to
`save: '='`
However when running the tests with `npm run test` I get an undefined function from this change:
`TypeError: undefined is not a constructor (evaluating 'scope.save()')`
which makes tests fail. In the end, either the tests fail or the function does not seem to be correctly referenced in the application but the tests pass... I spent more time than I would like to admit trying to solve this, any idea?

**Comment by jgadsden** [comment]
I will have a look today - hope we can put this in to version 1.3.1 as well

**Comment by jgadsden** [comment]
Hello @andk123 - I think the tests are complaining because '&' is specifying a method 'save' to be used in our scope. If we change it to '=' , this is a two way binding but it is not used for methods ?

**Comment by jgadsden** [comment]
Maybe something like this would work?
```
            scope:
            {
                dirty: '=',
                suggest: '=',
                threats: '=',
                type: '=',
                save: '&'
            }
```

via 

```
                            <tmt-element-threats suggest="vm.generateThreats" threats="vm.selected.threats" type="vm.diagram.diagramType" save="vm.edit" dirty="vm.dirty" />
```
